import { companyStampFields, defineModel, f } from '@nodeweaver/persistence';

export const inventoryModelCatalog = {
  Warehouse: defineModel('StockWarehouse', 'stock_warehouses', {
    ...companyStampFields({ updatedAt: false }),
    name: f('string', { required: true }),
    code: f('string'),
    lotStockLocationId: f('string'),
    inputLocationId: f('string'),
    outputLocationId: f('string'),
    scrapLocationId: f('string'),
    active: f('boolean', { default: true }),
  }),
  Location: defineModel('StockLocation', 'stock_locations', {
    ...companyStampFields({ updatedAt: false }),
    name: f('string', { required: true }),
    completeName: f('string'),
    usage: f('string', { default: 'internal' }),
    warehouseId: f('string'),
    parentId: f('string'),
    active: f('boolean', { default: true }),
  }),
  Quant: defineModel('StockQuant', 'stock_quants', {
    companyId: f('string', { index: true }),
    productId: f('string', { required: true, index: true }),
    locationId: f('string', { required: true, index: true }),
    lotId: f('string'),
    quantity: f('float', { default: 0 }),
    reservedQuantity: f('float', { default: 0 }),
    updatedAt: f('datetime', { default: 'now' }),
  }),
  Lot: defineModel('StockLot', 'stock_lots', {
    ...companyStampFields({ updatedAt: false }),
    name: f('string', { required: true }),
    productId: f('string', { required: true }),
  }),
  Picking: defineModel('StockPicking', 'stock_pickings', {
    ...companyStampFields({ updatedAt: false }),
    name: f('string'),
    pickingType: f('string', { default: 'internal' }),
    partnerId: f('string'),
    locationId: f('string'),
    locationDestId: f('string'),
    scheduledDate: f('datetime'),
    state: f('string', { default: 'draft' }),
    origin: f('string'),
    moveIds: f('string[]'),
    note: f('text'),
  }),
  Move: defineModel('StockMove', 'stock_moves', {
    ...companyStampFields({ updatedAt: false }),
    pickingId: f('string', { index: true }),
    name: f('string'),
    productId: f('string', { required: true }),
    productUomQty: f('float', { default: 0 }),
    quantityDone: f('float'),
    locationId: f('string'),
    locationDestId: f('string'),
    lotId: f('string'),
    state: f('string', { default: 'draft' }),
    priceUnit: f('float'),
  }),
  Adjustment: defineModel('StockAdjustment', 'stock_adjustments', {
    ...companyStampFields({ updatedAt: false }),
    name: f('string'),
    locationId: f('string'),
    productId: f('string'),
    theoreticalQty: f('float'),
    countedQty: f('float'),
    state: f('string', { default: 'draft' }),
  }),
} as const;
