import type { FieldDef, FieldType, ModelDef } from './types.js';

function prismaScalar(type: FieldType): string {
  switch (type) {
    case 'string':
    case 'text':
      return 'String';
    case 'boolean':
      return 'Boolean';
    case 'int':
      return 'Int';
    case 'float':
      return 'Float';
    case 'datetime':
      return 'DateTime';
    case 'json':
      return 'Json';
    case 'string[]':
      return 'String[]';
    default:
      return 'String';
  }
}

function fieldToPrismaLine(name: string, field: FieldDef): string {
  const parts: string[] = [name, prismaScalar(field.type)];
  const attrs: string[] = [];
  if (!field.required && field.type !== 'string[]') {
    // optional
    if (!parts[1]!.endsWith('?') && field.type !== 'json') {
      parts[1] = `${parts[1]}?`;
    } else if (field.type === 'json') {
      parts[1] = 'Json?';
    }
  }
  if (field.default === 'now' && field.type === 'datetime') {
    attrs.push('@default(now())');
  } else if (field.default !== undefined && field.default !== 'now') {
    if (typeof field.default === 'string') {
      attrs.push(`@default("${field.default}")`);
    } else if (typeof field.default === 'boolean' || typeof field.default === 'number') {
      attrs.push(`@default(${field.default})`);
    }
  }
  if (field.index) attrs.push('@index');
  return `  ${parts.join(' ')}${attrs.length ? ` ${attrs.join(' ')}` : ''}`;
}

/**
 * Emit a Prisma `model` block for paste into `schema.prisma`.
 * Prisma cannot register models at runtime — this is the supported integration path.
 */
export function toPrismaModel(model: ModelDef): string {
  const lines: string[] = [`model ${model.name} {`];

  if (model.id === 'uuid') {
    lines.push('  id String @id @default(uuid())');
  } else if (model.id === 'objectId') {
    lines.push('  id String @id @default(cuid()) @map("_id")');
  } else {
    lines.push('  id Int @id @default(autoincrement())');
  }

  for (const [key, field] of Object.entries(model.fields)) {
    lines.push(fieldToPrismaLine(key, field));
  }

  lines.push(`  @@map("${model.table}")`);
  lines.push('}');
  return lines.join('\n');
}

export function toPrismaSchemaFragment(
  models: Record<string, ModelDef>,
  header?: string,
): string {
  const blocks = Object.values(models).map(toPrismaModel);
  const preface =
    header ??
    '// Generated by @nodeweaver/persistence — paste into schema.prisma (or merge via codegen).';
  return `${preface}\n\n${blocks.join('\n\n')}\n`;
}
