import { companyStampFields, defineModel, f } from '@nodeweaver/persistence';

export const accountingModelCatalog = {
  Account: defineModel('AccountAccount', 'account_accounts', {
    ...companyStampFields({ updatedAt: false }),
    code: f('string', { required: true }),
    name: f('string', { required: true }),
    accountType: f('string', { default: 'asset' }),
    reconcile: f('boolean', { default: false }),
    active: f('boolean', { default: true }),
  }),
  Journal: defineModel('AccountJournal', 'account_journals', {
    ...companyStampFields({ updatedAt: false }),
    name: f('string', { required: true }),
    code: f('string'),
    journalType: f('string', { default: 'general' }),
    defaultAccountId: f('string'),
    active: f('boolean', { default: true }),
  }),
  Move: defineModel('AccountMove', 'account_moves', {
    ...companyStampFields({ updatedAt: false }),
    name: f('string'),
    ref: f('string'),
    journalId: f('string'),
    date: f('string'),
    state: f('string', { default: 'draft' }),
    partnerId: f('string'),
    sourceModel: f('string'),
    sourceId: f('string'),
    lineIds: f('string[]'),
  }),
  MoveLine: defineModel('AccountMoveLine', 'account_move_lines', {
    companyId: f('string', { index: true }),
    moveId: f('string', { index: true }),
    accountId: f('string', { required: true }),
    partnerId: f('string'),
    name: f('string'),
    debit: f('float', { default: 0 }),
    credit: f('float', { default: 0 }),
    taxId: f('string'),
    productId: f('string'),
    quantity: f('float'),
    priceUnit: f('float'),
  }),
  Invoice: defineModel('AccountInvoice', 'account_invoices', {
    ...companyStampFields({ updatedAt: false }),
    name: f('string'),
    partnerId: f('string'),
    moveType: f('string', { default: 'out_invoice' }),
    invoiceDate: f('string'),
    state: f('string', { default: 'draft' }),
    amountUntaxed: f('float'),
    amountTax: f('float'),
    amountTotal: f('float'),
    amountResidual: f('float'),
    moveId: f('string'),
    journalId: f('string'),
    lineIds: f('string[]'),
    narrations: f('text'),
  }),
  InvoiceLine: defineModel('AccountInvoiceLine', 'account_invoice_lines', {
    companyId: f('string', { index: true }),
    invoiceId: f('string', { index: true }),
    productId: f('string'),
    name: f('string'),
    quantity: f('float'),
    priceUnit: f('float'),
    taxIds: f('string[]'),
    accountId: f('string'),
    subtotal: f('float'),
  }),
  Payment: defineModel('AccountPayment', 'account_payments', {
    ...companyStampFields(),
    name: f('string'),
    partnerId: f('string'),
    amount: f('float'),
    paymentType: f('string', { default: 'inbound' }),
    journalId: f('string'),
    invoiceId: f('string'),
    moveId: f('string'),
    state: f('string', { default: 'draft' }),
    paymentDate: f('string'),
  }),
} as const;
